### ISSUE TITLE
Error trying to retrieve data from indices located in "euro zone" or "world"

### ISSUE THREAD

**Issue by GitHunter0** [alvarobartt/investpy#226]
Hey @alvarobartt , I'm still having issue #53  with investpy version 1.0.

For example, this returns the error message "RuntimeError: ERR#0034: country euro zone not found, check if it is correct.":
`investpy.get_index_recent_data(index='STOXX 600', country='euro zone', order='ascending', interval='Daily')`

Is there a workaround? I hope so, investpy is a fantastic package.

**Comment by alvarobartt** [comment]
Hi @GitHunter0! 🤗 Thank you for your kind words and sorry for taking so long to answer!

This has already been fixed by @se-jaeger in https://github.com/alvarobartt/investpy/pull/217, so in order to update investpy so that you have all the latest features, please install it using the following command and everything should be fixed:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Just let me know! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by GitHunter0** [comment]
@alvarobartt , no problem man, thank you for the response!
I followed the instruction, however I am still receiving this message error "RuntimeError: ERR#0034: country euro zone not found, check if it is correct."
Maybe it is some problem with git installation method, would you please consider push the updated investpy to pip repository, so that I can run another test? (also it is faster to install and beginners-friendly)

**Comment by alvarobartt** [comment]
Sure @GitHunter0! Probably later today I'll upload to PyPI the updated version (probably 1.1beta), so that you can easily install it and test it so as to see if the issue is fixed. 👍🏻

**Comment by GitHunter0** [comment]
Hey @alvarobartt, I appreciate! Please let us know when you release version 1.1beta at pip 👍🏻
PS: Just one doubt, are you sure the fix of #217 from @se-jaeger is in the master branch?

**Comment by alvarobartt** [comment]
Sure @GitHunter0 I just checked it and it was already merged into the master branch! Will try to release it later today, I've been mad busy these days... 👍🏻

**Comment by pourquoi42** [comment]
I just installed investpy from master. I agree with GitHunter0.... the issue still remains.

**Comment by alvarobartt** [comment]
@GitHunter0 @pourquoi42 Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩 Now both "world" and "euro zone" data retrieval is available!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:
